# Generated by Django 5.2.4 on 2025-07-08 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missioncontrole',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operationcontrole',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
