# Generated by Django 5.2.2 on 2025-07-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0002_alter_missioncontrole_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operationcontrole',
            unique_together={('gamme', 'ordre')},
        ),
    ]
