# Generated by Django 5.2.2 on 2025-07-15 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0005_gammecontrole_version_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photooperation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
