# Generated by Django 5.2.4 on 2025-07-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0007_profil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profil',
            new_name='profile',
        ),
    ]
