# Generated by Django 5.2.4 on 2025-07-28 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0012_user_is_admin_alter_user_is_op_alter_user_is_rs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ro',
            field=models.BooleanField(default=False, verbose_name='RO'),
        ),
        migrations.AlterField(
            model_name='photooperation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_operation_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhotoDefaut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.CharField(max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_defaut_created', to=settings.AUTH_USER_MODEL)),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamme.gammecontrole')),
            ],
        ),
    ]
