# Generated by Django 5.2.2 on 2025-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0016_epi_moyens_controle_alter_photodefaut_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gammecontrole',
            name='picto_s_r',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('R', 'R')], default='S', max_length=1, null=True),
        ),
    ]
