# Generated by Django 5.2.2 on 2025-08-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0017_gammecontrole_picto_s_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationcontrole',
            name='moyen_controle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Moyen de contrôle'),
        ),
    ]
