# Generated by Django 5.2.2 on 2025-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0018_operationcontrole_moyen_controle'),
    ]

    operations = [
        migrations.AddField(
            model_name='gammecontrole',
            name='epis',
            field=models.ManyToManyField(blank=True, related_name='gammes', to='Gamme.epi', verbose_name='Équipements de Protection Individuelle'),
        ),
    ]
