# Generated by Django 5.2.2 on 2025-08-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0019_gammecontrole_epis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationcontrole',
            name='moyenscontrole',
        ),
        migrations.AddField(
            model_name='operationcontrole',
            name='moyenscontrole',
            field=models.ManyToManyField(blank=True, related_name='operations', to='Gamme.moyens_controle'),
        ),
    ]
