# Generated by Django 5.2.2 on 2025-08-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0020_remove_operationcontrole_moyenscontrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gammecontrole',
            name='moyens_controle',
            field=models.ManyToManyField(blank=True, related_name='gammes', to='Gamme.moyens_controle', verbose_name='Moyens de Contrôle'),
        ),
    ]
