# Generated by Django 5.2.2 on 2025-08-07 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0022_remove_gammecontrole_picto_s_r_gammecontrole_picto_r_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validation',
            options={'verbose_name': 'Validation', 'verbose_name_plural': 'Validations'},
        ),
        migrations.AddField(
            model_name='validation',
            name='gamme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='Gamme.gammecontrole'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='Gamme.operationcontrole'),
        ),
        migrations.AddConstraint(
            model_name='validation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation__isnull', False), ('gamme__isnull', False), _connector='OR'), models.Q(('gamme__isnull', False), ('operation__isnull', False), _negated=True)), name='only_one_validation_target', violation_error_message='Une validation doit être liée soit à une opération, soit à une gamme, mais pas aux deux.'),
        ),
    ]
