# Generated by Django 5.2.2 on 2025-08-21 10:09

import Gamme.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0024_gammecontrole_est_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gammecontrole',
            name='photo_traitement_non_conforme',
            field=models.ImageField(blank=True, null=True, upload_to=Gamme.models.GammeControle.photo_traitement_non_conforme_upload_to),
        ),
        migrations.CreateModel(
            name='Photolimiteacceptable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=Gamme.models.photo_defaut_upload_to)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limiteacceptable_created', to=settings.AUTH_USER_MODEL)),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limiteacceptable_photos', to='Gamme.gammecontrole')),
            ],
            options={
                'verbose_name': 'Photo de limite acceptable',
                'verbose_name_plural': 'Photos de limite acceptable',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
