# Generated by Django 5.2.4 on 2025-07-15 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0003_alter_operationcontrole_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='gammecontrole',
            name='version_num',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gammecontrole',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gammes', to='Gamme.missioncontrole'),
        ),
    ]
