# Generated by Django 5.2.4 on 2025-07-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0009_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
