# Generated by Django 5.2.4 on 2025-07-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0010_remove_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
