# Generated by Django 5.2.2 on 2025-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0011_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_op',
            field=models.BooleanField(default=False, verbose_name='Opérateur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_rs',
            field=models.BooleanField(default=False, verbose_name='Responsable'),
        ),
    ]
