# Generated by Django 5.2.2 on 2025-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0013_user_is_ro_alter_photooperation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gammecontrole',
            name='No_incident',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
