# Generated by Django 5.2.4 on 2025-07-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0014_gammecontrole_no_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioncontrole',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='gammes_pdf/'),
        ),
    ]
