# Generated by Django 5.2.2 on 2025-08-01 12:59

import Gamme.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0015_missioncontrole_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='epi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/epi/')),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='moyens_controle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/moyens_controle/')),
                ('ordre', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='photodefaut',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Photo de défaut', 'verbose_name_plural': 'Photos de défaut'},
        ),
        migrations.RenameField(
            model_name='missioncontrole',
            old_name='produitref',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='gammecontrole',
            name='Num_gamme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gammecontrole',
            name='Temps_alloué',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gammecontrole',
            name='commantaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gammecontrole',
            name='commantaire_identification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gammecontrole',
            name='commantaire_traitement_non_conforme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gammecontrole',
            name='photo_traitement_non_conforme',
            field=models.ImageField(blank=True, null=True, upload_to='photos/non_conformes/gamme_{instance.gamme.id}/{filename}'),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='missioncontrole',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operationcontrole',
            name='frequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='operationcontrole',
            name='criteres',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='operationcontrole',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='operationcontrole',
            name='gamme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='Gamme.gammecontrole'),
        ),
        migrations.AlterField(
            model_name='operationcontrole',
            name='ordre',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='operationcontrole',
            name='titre',
            field=models.CharField(default='Nouvelle opération', max_length=100),
        ),
        migrations.AlterField(
            model_name='operationcontrole',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photodefaut',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_defaut_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photodefaut',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='photodefaut',
            name='gamme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaut_photos', to='Gamme.gammecontrole'),
        ),
        migrations.AlterField(
            model_name='photodefaut',
            name='image',
            field=models.ImageField(upload_to=Gamme.models.photo_defaut_upload_to),
        ),
        migrations.AddField(
            model_name='operationcontrole',
            name='moyenscontrole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gamme.moyens_controle'),
        ),
        migrations.CreateModel(
            name='validation',
            fields=[
                ('id_validation', models.AutoField(primary_key=True, serialize=False)),
                ('date_validation_user_ro', models.DateTimeField(auto_now_add=True)),
                ('date_validation_user_clt', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='Gamme.operationcontrole')),
                ('user_clt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_clt', to=settings.AUTH_USER_MODEL)),
                ('user_ro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_ro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
