# Generated by Django 5.2.2 on 2025-08-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0021_gammecontrole_moyens_controle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gammecontrole',
            name='picto_s_r',
        ),
        migrations.AddField(
            model_name='gammecontrole',
            name='picto_r',
            field=models.BooleanField(default=False, verbose_name='Picto R'),
        ),
        migrations.AddField(
            model_name='gammecontrole',
            name='picto_s',
            field=models.BooleanField(default=False, verbose_name='Picto S'),
        ),
    ]
