# Generated by Django 5.2.2 on 2025-08-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamme', '0023_alter_validation_options_validation_gamme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gammecontrole',
            name='est_active',
            field=models.BooleanField(default=True, verbose_name='Est active'),
        ),
    ]
